type ProjectArgs = {
  heroImageID: number
}

export const agencyProject1 = ({ heroImageID }: ProjectArgs) => {
  return {
    slug: 'golf-leaderboard',
    _status: 'published' as const,
    title: 'Realtime leaderboard for international golf events',
    projectType: 'agency' as const,
    projectStatus: 'completed' as const,
    heroImage: heroImageID,
    excerpt:
      'Processing real-time data feeds to display invidivdual and team leaderboards on the course and in hospitality',
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The Mighty Challenge',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our client, a global professional services firm with over 5,000 employees, was operating on a 15-year-old CRM system that had become a bottleneck for their sales and client management teams. The system was slow, unintuitive, and lacked integration with modern tools.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            textStyle: '',
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our Approach',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'We conducted extensive user research across multiple offices and departments to understand pain points and requirements. Rather than a simple lift-and-shift, we redesigned workflows and data structures to match how the business actually operates today.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            textStyle: '',
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Outcomes',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'list',
            listType: 'bullet',
            tag: 'ul',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '60% reduction in time spent on routine CRM tasks',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '95% user adoption within first 3 months',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 2,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Seamless integration with Outlook, Teams, and other Microsoft 365 tools',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 3,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Real-time reporting and analytics dashboard',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 4,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Zero data loss during migration',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 5,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    technologies: [{ tech: 'React' }, { tech: 'Vite' }, { tech: 'Tailwind' }, { tech: 'Render' }],
    links: {
      website: '',
      caseStudy: 'https://example.com/case-studies/crm-modernisation',
      repository: '',
    },
    meta: {
      title: 'Realtime leaderboard for international golf events | HCE Studio',
      description:
        'Processing real-time data feeds to display invidivdual and team leaderboards on the course and in hospitality',
      image: heroImageID,
    },
  }
}

export const agencyProject2 = ({ heroImageID }: ProjectArgs) => {
  return {
    slug: 'dynamic-golf-shot-tracer-poc',
    _status: 'published' as const,
    title: 'Dynamic golf shot tracer',
    projectType: 'agency' as const,
    projectStatus: 'proof-of-concept' as const,
    heroImage: heroImageID,
    excerpt:
      'Tracing the tee-shot arcs of a golf tournament, with a custom AI Dynamic Director choosing the shots and holes to display',
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Putting Values First',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our client is a UK-based sustainable fashion brand committed to transparency and ethical production. They needed an e-commerce platform that could tell the story of each garment—from the organic farm where the cotton was grown to the fair-trade factory where it was sewn—without compromising on performance or user experience.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            textStyle: '',
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Technical Innovation',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'We built a headless commerce platform using modern JAMstack architecture for lightning-fast page loads and SEO performance. Each product includes a detailed sustainability scorecard, supplier information, and environmental impact data, all managed through an intuitive CMS.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            textStyle: '',
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Key Features',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'list',
            listType: 'bullet',
            tag: 'ul',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Product sustainability scorecards and supply chain transparency',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Carbon-neutral hosting and optimised for minimal environmental impact',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 2,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Integration with ethical payment processors',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 3,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Size recommendation engine to reduce returns',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 4,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Multi-currency and international shipping',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 5,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Since launch, the platform has helped the brand grow their online revenue by 240% whilst maintaining their commitment to transparency and sustainability.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            textStyle: '',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    technologies: [
      { tech: 'React' },
      { tech: 'Three.js' },
      { tech: 'Node' },
      { tech: 'Express' },
      { tech: 'PostgreSQL' },
      { tech: 'Render' },
    ],
    links: {
      website: 'https://example.com/sustainable-fashion',
      caseStudy: 'https://example.com/case-studies/sustainable-fashion',
      repository: '',
    },
    meta: {
      title: 'Dynamic golf shot tracer | HCE Studio',
      description:
        'Tracing the tee-shot arcs of a golf tournament, with a custom AI Dynamic Director choosing the shots and holes to display',
      image: heroImageID,
    },
  }
}

export const ventureProject1 = ({ heroImageID }: ProjectArgs) => {
  return {
    slug: 'ordinary-mastery-platform',
    _status: 'published' as const,
    title: 'Ordinary Mastery Platform',
    projectType: 'venture' as const,
    projectStatus: 'in-development' as const,
    heroImage: heroImageID,
    excerpt:
      "An intelligent platform that helps you learn new skills and build the habits you've always wanted to",
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Reimagining personal growth',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Traditional market research is expensive, time-consuming, and often inaccessible to smaller organisations. Our AI-powered platform changes that by combining automated data gathering, intelligent analysis, and expert validation to deliver actionable insights at a fraction of the traditional cost.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            textStyle: '',
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Key Features',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'list',
            listType: 'bullet',
            tag: 'ul',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Automated data collection from multiple sources',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'AI-driven analysis and trend identification',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 2,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Expert validation and contextualisation',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 3,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Interactive dashboards and reporting',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 4,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Collaborative workspace for teams',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 5,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Current Status',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Currently in development with pilot customers providing feedback. Expected beta launch in Q2 2026.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            textStyle: '',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    technologies: [{ tech: 'Helix CMS' }, { tech: 'MySQL' }],
    links: {
      website: 'https://ordinarymastery.com',
      caseStudy: '',
      repository: '',
    },
    meta: {
      title: 'Ordinary Mastery Platform | HCE Studio',
      description:
        "An intelligent platform that helps you learn new skills and build the habits you've always wanted to",
      image: heroImageID,
    },
  }
}
